### PR TITLE
Merge Mudlet's autocompletion back into master

### PR DESCRIPTION
**Pull request by vadi2**
We've been using the autocompletion feature in production for a couple of years now and it works well.

### CODE REVIEW

**Comment by gamecreature** [comment]
I will look into this!
Seemed that I missed this pull request. (Missed the GitHub-email)

**Comment by gamecreature** [comment]
Hi @vadi2 I'm looking at the code and figuring out if I can merge this.. 

What is the argument 'kind' ?
Where is it coming from.. There are some hardcoded kind-constants used:
item->kind() == 14 ... 
kind == 3  ? label  + "()" : details

Also the info-screen looks very application specific. (special handling of details and void type)

**Comment by vadi2** [comment]
@dicene

**Comment by dicene** [comment]
I had to dig a bit to figure out where they came from. I'm a lot more wary of magic constants that I used to be. I found where they came from though: https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_completion

**Comment by dicene** [comment]
Was wanting to come up with a way to differentiate between functions and Lua reserved words, so I decided to try and use the constants that the LSP was using, since I remembered Edbee wanting to be adapted to be LangServ friendly.

**Comment by gamecreature** [comment]
I just merged this branch.  (With some changes).
Please note autocomplete is on by default. Number of characters to enter before completion kicks in is 0 by default. (Can be configured)
Added the langserver constants. 
And fixed a memory leak in QTextEditorAutocompleteComponent. (QMenu was not owned and not deleted)

**Pull request merged**
