### PR TITLE
Modify build process to turn off onig warnings

### PR DESCRIPTION
**Pull request by keneanung**
The compilation of onig throws a few thousand warnings about ctype declaration.
Since it is a 3rd party library, those warnings may be undesired. This commit
modifys the build process to silence those warnings.

### CODE REVIEW

**Comment by vadi2** [comment]
This change is pretty important because otherwise Travis-CI build logs are blown out of proportion and don't even fit anymore on the page, [see example](https://travis-ci.org/Mudlet/Mudlet/jobs/230489310).

**Comment by keneanung** [comment]
Actually, hold on to this PR for a bit. Looks like my testing was incomplete and the settings are not quite what we'd want for onig...

**Comment by gamecreature** [comment]
I really appreciatie the work you've put into this...
I will wait for your testing ..
It is important that it still compiles on all platform.

**Comment by keneanung** [comment]
I can't promise to have everything available for testing, but what compromises "all" platforms? I haven't seen a list of supported platforms yet...

**Comment by gamecreature** [comment]
Every platform is impossible of course..
But I mean the most important platform
- windows 
- os x
- linux (clang / gcc compile)
I usually develop on OS X and once in a while I test it in Windows...

**Comment by keneanung** [comment]
I successfully tested the following:
- macOS
- linux gcc

The others were not (yet?)
- I have no Windows compile environment right now
- I can't get linux clang builds to run (neither `master` nor this branch)

**Comment by gamecreature** [comment]
I you let me know when your done with this pull-request,
I will try to boot my Windows environment again to test it. 
Thanks!

Library building/linking etc on Windows is something I've had issues with in the past, so it's something I would like to test before the merge

**Comment by keneanung** [comment]
I'm done to the best of my abilities... If you have any tips to get clang running under Ubuntu, I can try it, but I have no idea what to try further...

**Comment by keneanung** [comment]
Update: I got it to compile with clang under Ubuntu with Qt 5.6.

Qt 5.7 failed because it didn't know my clang could use the c++ 11 standard, no idea why. Another project works

Qt 5.8 fails due to #4, but looks like it would work otherwise.

**Comment by keneanung** [comment]
@gamecreature I'm done testing this on all machines I have access to, btw.

**Comment by gamecreature** [comment]
@keneanung  Thanks for testing
I really hope to find a time slot this week to run it on my Windows machine.. (Has been a long time since I've booted it. Need to update the environment again etc.)

**Comment by gamecreature** [comment]
I just tried to compile the edbee-app with this pull-request. (Mac OS X Build)
I breaks the edbee-app project.  Because onig isn't placed in the edbee library anymore.

```
Undefined symbols for architecture x86_64:
  "_OnigDefaultSyntax", referenced from:
      edbee::OnigRegExpEngine::OnigRegExpEngine(QString const&, bool, edbee::RegExp::Syntax) in libedbee.a(regexp.o)
  "_OnigEncodingUTF_16LE", referenced from:
      edbee::OnigRegExpEngine::OnigRegExpEngine(QString const&, bool, edbee::RegExp::Syntax) in libedbee.a(regexp.o)
  "_OnigSyntaxASIS", referenced from:
      edbee::OnigRegExpEngine::OnigRegExpEngine(QString const&, bool, edbee::RegExp::Syntax) in libedbee.a(regexp.o)
  "_OnigSyntaxRuby", referenced from:
 ...
```

This construct makes using edbee more difficult. Because with the current version only adding  the following line to your project was enough. Or you only needed to include 1 library file.
```
include("vendor/edbee-lib/edbee-lib/edbee-lib.pri");
```
I'm going to do some more testing, because for me it's a priority that using edbee in your project shouldn't be difficult..

I going to investigate the option to disable the warnings via #pragma directives (for clang and gcc).

**Comment by gamecreature** [comment]
I just committed a fix to the master branch. Which doesn't alter the build process with libraries.
I only adds a few pragma's to silence the warnings.. 
(I haven't tested visual studio)

**Comment by keneanung** [comment]
gcc now complains about the clang pragmas, but those are far fewer warnings than the original onig ones. :+1:

**Comment by gamecreature** [comment]
Just added a check for clang for the clang pragma's.

**Comment by keneanung** [comment]
Two more pragma warnings: https://travis-ci.org/edbee/edbee-lib/jobs/232773881#L334 and a few lines below :grin:

**Comment by gamecreature** [comment]
Fixed! 
Btw. It's nice to have Travis testing the linux builds  :)

**Comment by keneanung** [comment]
I know, right :laughing:

**Pull request closed without merging**
