### PR TITLE
Update: bring QsLog up to date

### PR DESCRIPTION
**Pull request by SlySven**
This commit replaces the code originally used in pretty much the first commit with the current version of the QsLog code from: https://bitbucket.org/codeimproved/qslog as of commit: 46b643d5bcbc .

This was done because the original code is showing signs of its age with current compilers and throwing up warnings.

The option to include file and line numbers has changed in name slightly and the qmake and cmake project files from the updated source code have been amended to have that option enabled by default as the original code had.

Some superfluous "example" code has been pruned as a sub-directory in the replacement code used.

It was also necessary to modify the logging.h header in the edbee/util superproject directory so that it used a non-system #include for the QsLog header.

I have updated the Qt include project file so that it lists some more files in the Qt Creator (the Qt IDE) relating to the main edbee-lib superproject.

Signed-off-by: Stephen Lyons <slysven@virginmedia.com>

### CODE REVIEW

**Comment by vadi2** [comment]
@gamecreature could this be merged? QsLog uses `auto_ptr` which was depricated in C++11 and now removed in C++17 - so QsLog no longer compiles when using some compilers with a strict C++17 mode.

**Comment by gamecreature** [comment]
@SlySven Sorry for the late response I will check this out.

**Comment by gamecreature** [comment]
@SlySven I've tried to build you pull request, but it failed to compile. 

After changing in edbee-lib/test/main.cpp:45-46.  (Using DestinationPtrU and std::move it seems to compile again)

```cpp
    static QsLogging::DestinationPtrU debugDestination( QsLogging::DestinationFactory::MakeDebugOutputDestination() );
    logger.addDestination(std::move(debugDestination));

```
@SlySven  embedding this pull-request will make edbee dependent on c++11. Which it currently isn't. (std::move is c++11)

**Comment by vadi2** [comment]
I think there's not too many that we can conduct a survey of them.

**Comment by gamecreature** [comment]
I have to agree with you...  I will tag a non-c++11 version and move forward with it..
(I have to check our own older internal projects)

**Pull request merged**
